apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: simple-fsm-gateway
spec:
  gatewayClassName: fsm-gateway-cls
  listeners:
  - protocol: HTTP
    port: 8000
    name: http
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcbin
  name: grpcbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      containers:
        - image: flomesh/grpcbin
          name: grpcbin
          ports:
            - name: grpc
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcbin
  name: grpcbin
spec:
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: grpcbin
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc-route
spec:
  parentRefs:
    - name: simple-fsm-gateway
      port: 8000
  rules:
  - matches:
    - method:
        service: hello.HelloService
        method: SayHello
    backendRefs:
    - name: grpcbin
      port: 9000